---
abstract: unknown
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-RequestBase
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 1.90
version: 0.1
